# 1. Introduction
__Global Energy Consumption__ has increased rapidly over the past few years due to industrilization, population growth, urban developement, and technological advancement. The Excessive dependence on fossil fuels such as coal, oil, and natural gas has led to serious environmental challenges including climate change, global warming, and increasig carbon dioxide (CO<sub>2</sub>) emissions.

The dataset provides __five years (2020-2024)__ of data combining __global energy consumption__ statistics for __50__ countries across all continents.

### The project focuses on:
- Renewable vs non-renewable energy usage
- CO₂ emissions trends
- GDP and population relationship with energy usage
- Country-wise energy efficiency
- Future sustainability insights
- SQL integration for analytical queries
- Predictive analysis using Machine Learning

By analyzing these factors, the project provides actionable insights and recommendations that can help in promoting renewable energy adoption, improving energy efficiency, and supporting sustainable developement goals.

---
# 2. Tools & Technologies Used
- Python(pandas, Numpy)
- Data Visualization(Matplotlib, Seaborn, Plotly)
- Database(MySQL/SQLite)
- ML (Scikit-learn)
- Dashboard(Streamlit)
- Notebook(Jupyter)
---

### Dataset Source
- [Global Energy - by Our world](http://ourworldindata.org/energy)

# 3. Import Libraries

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import sqlite3

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

import warnings
warnings.filterwarnings('ignore')

# 4. Loading Data

In [22]:
df = pd.read_csv("../Dataset/global_climate_energy.csv", lineterminator="\n")

In [23]:
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy\r
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,\r
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,\r
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,\r
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,\r
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,\r

In [28]:
columns = [

    'country',
    'year',
    'population',
    'gdp',

    'primary_energy_consumption',
    'energy_per_capita',
    'energy_per_gdp',

    'electricity_generation',
    'electricity_demand',

    'fossil_fuel_consumption',
    'fossil_share_energy',

    'coal_consumption',
    'oil_consumption',
    'gas_consumption',

    'renewables_consumption',
    'renewables_share_energy',

    'solar_consumption',
    'wind_consumption',
    'hydro_consumption',

    'low_carbon_consumption',

    'greenhouse_gas_emissions'
]

df_main=df[columns]

In [30]:
df_main.head(10)

,country,year,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp,electricity_generation,electricity_demand,fossil_fuel_consumption,...,coal_consumption,oil_consumption,gas_consumption,renewables_consumption,renewables_share_energy,solar_consumption,wind_consumption,hydro_consumption,low_carbon_consumption,greenhouse_gas_emissions
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,378.61,378.61,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216.89
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,404.85,404.85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,231.01
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,433.19,433.19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,248.23
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,458.24,458.24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.56
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,496.56,496.56,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,289.95
5,ASEAN (Ember),2005,NaN,NaN,NaN,NaN,NaN,522.68,522.68,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,306.06
6,ASEAN (Ember),2006,NaN,NaN,NaN,NaN,NaN,547.19,547.19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,319.99
7,ASEAN (Ember),2007,NaN,NaN,NaN,NaN,NaN,579.04,579.04,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,340.76
8,ASEAN (Ember),2008,NaN,NaN,NaN,NaN,NaN,603.85,603.85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,349.48
9,ASEAN (Ember),2009,NaN,NaN,NaN,NaN,NaN,624.46,624.46,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,362.09

The dataset contains 36540 rows of 50 unique countries and have 10 columns:
- date
- country name
- average temperature
- humidity
- CO<sub>2</sub> emision
- energy consumption
- renewable share
- urban population
- industrial activity index
- energy price

# 5. Data Cleaning

### 5.1 Check Missing value

In [32]:
df_main.isnull().sum()

country                           0
year                              0
population                     4466
gdp                           11415
primary_energy_consumption     9940
energy_per_capita             12109
energy_per_gdp                15313
electricity_generation        15214
electricity_demand            17093
fossil_fuel_consumption       16790
fossil_share_energy           16816
coal_consumption              16790
oil_consumption               16790
gas_consumption               16790
renewables_consumption        16790
renewables_share_energy       16816
solar_consumption             16790
wind_consumption              16790
hydro_consumption             16790
low_carbon_consumption        16790
greenhouse_gas_emissions      17435
dtype: int64

### 5.2 Check Duplicate Rows

In [ ]:
print(df.duplicated().sum())

__Data is already clean and niether have missing values nor duplicate rows__

# 6. Feature Engineering

### 6.1 Non-Renewable consuption share Column

In [ ]:
df["non_renewable_share"] = (100 - df["renewable_share"])

### 6.2 Energy Per Capita

In [ ]:
df["energy_per_capita"] = (df["energy_consumption"] / df["urban_population"])

### 6.3 CO<sub>2</sub> Per Capita

In [ ]:
df["co2_per_capita"] = (df["co2_emission"] / df["urban_population"])

### 6.4 Year column

In [ ]:
df["year"]=pd.to_datetime(df['date']).dt.year

In [ ]:
df.head()

# 7. Exploratory Data Analysis (EDA)

### 7.1 Top Energy Consuming Countries

In [ ]:
country_energy= df.groupby('country')['energy_consumption'].sum().sort_values(ascending=False)
sns.barplot(x=country_energy.values, y=country_energy.index, palette="coolwarm")


plt.title("Energy consumption by country")
plt.xlabel("Energy Consumption")
plt.ylabel("Country")
plt.show()

### 7.2 Renewable Energy Trend Over Time

In [ ]:
sns.lineplot(data=df, x="year", y="renewable_share")
plt.title('Renewable Energy Trend Over Time')
plt.xlabel('Year')
plt.ylabel('Renewable Energy')
plt.show()

### 7.3 CO<sub>2</sub> Emission Trend

In [ ]:
sns.lineplot(data=df, x="year", y="co2_emission", markers="o")
plt.title('Average CO₂ Emission Trend')
plt.xlabel('Year')
plt.ylabel('CO₂ Emission')
plt.show()

### 7.4 Correlation Heatmap

In [ ]:
plt.figure(figsize=(14,10))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()